# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjbaiAvdCFOLoHMaCLqydvUx8PD18Mce
"""

import os
import librosa
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from google.colab import files

# 1. CREATE DUMMY FOLDERS (You should upload your real .wav files into these)
folders = ['gunshot', 'reload', 'slide_battery']
for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Check the folder icon on the left. Upload your audio files into the correct folders now.")

def extract_features(file_path):
    try:
        audio, sample_rate = librosa.load(file_path, res_type='kaiser_fast')
        mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
        return np.mean(mfccs.T, axis=0)
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

# 2. THE TRAINING LOOP
def train_my_model():
    X, y = [], []
    for i, label in enumerate(folders):
        for file in os.listdir(label):
            if file.endswith('.wav'):
                data = extract_features(os.path.join(label, file))
                if data is not None:
                    X.append(data)
                    y.append(i)

    X = np.array(X)
    y = np.array(y)

    model = models.Sequential([
        layers.Dense(256, activation='relu', input_shape=(40,)),
        layers.Dropout(0.3),
        layers.Dense(128, activation='relu'),
        layers.Dense(3, activation='softmax') # 3 categories
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(X, y, epochs=100) # Training...

    model.save('shot_timer_model.h5')
    print("Model saved! Downloading now...")
    files.download('shot_timer_model.h5')

# Run this once you've uploaded your files
# train_my_model()